message condition if the image failed to run

diff --git a/.github/workflows/matrix-configuration.yml b/.github/workflows/matrix-configuration.yml
--- a/.github/workflows/matrix-configuration.yml
+++ b/.github/workflows/matrix-configuration.yml
@@ -24,5 +24,5 @@ jobs:
               run: docker info
 
             - name: Run images on ${{ matrix.sistemas-operativos }}
-              if: success() || failure()
-              run: docker run ${{ matrix.imagenes }}
+              run: |
+               docker run ${{ matrix.imagenes }} || echo "The image ${{ matrix.imagenes }} failed to run"
